---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: America/New_York
    labels:
      - dependencies
      - docker
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/docs/examples/dockerfile"
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: America/New_York
    labels:
      - dependencies
      - docker
    groups:
      example-docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: America/New_York
    labels:
      - dependencies
      - github-actions
    groups:
      action-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ci
      include: scope
