---
# markdownlint --config .markdownlint.yaml --ignore LICENSE.md *.md

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD001/heading-increment - Heading levels should only increment by one level at a time
MD001: true

# MD003/heading-style - Heading style
MD003:
  # Heading style should be consistent
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "consistent"

# MD005/list-indent - Inconsistent indentation for list items
MD005: true

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  br_spaces: 2 # Number of spaces for line break
  strict: false # Don't check inside code blocks

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: true # Check code blocks
  spaces_per_tab: 2

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 1

# MD013/line-length - Line length
MD013:
  line_length: 80
  code_blocks: false
  tables: false
  headings: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true # Only check sibling headings

# MD025/single-title/single-h1 - Multiple top-level headings
MD025:
  level: 1
  front_matter_title: ""

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: "one_or_ordered"

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: true

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements: []

# MD034/no-bare-urls - Bare URLs should be enclosed in angle brackets
MD034: true

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036:
  punctuation: ".,;:!?。，；：！？"

# MD037/no-space-in-emphasis - Spaces inside emphasis markers
MD037: true

# MD038/no-space-in-code - Spaces inside code span elements
MD038: true

# MD039/no-space-in-links - Spaces inside link text
MD039: true

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041:
  level: 1
  front_matter_title: ""

# MD042/no-empty-links - No empty links
MD042: true

# MD043/required-headings - Required heading structure
MD043: false # Disabled by default

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  names: []
  code_blocks: false

# MD045/no-alt-text - Images should have alternate text
MD045: true

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"
