---
extends: default
rules:
    line-length:
        max: 120
        level: warning
    indentation:
        indent-sequences: consistent
    comments:
        require-starting-space: true
        ignore-shebangs: true
        min-spaces-from-content: 1
