---
services:
  caddy:
    image: "ghcr.io/thimslugga/caddy-cloudflare:${CADDY_IMAGE_VERSION:?set CADDY_IMAGE_VERSION in .env}"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - "../caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/data"
      - "caddy-config:/config"

volumes:
  caddy-data:
  caddy-config:
