name: caddy-cloudflare OCI build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "Dockerfile.alpine"
      - "VERSION"
  #  paths-ignore:
  #    - "README.md"
  #pull_request:
  #  branches:
  #    - main
  #  paths-ignore:
  #    - "README.md"

jobs:
  build-and-push-images:
    if: github.repository == 'thimslugga/caddy-cloudflare'
    timeout-minutes: 15
    name: Build and push images
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
      #pull-requests: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        id: checkout

      - name: Configure Version
        shell: bash
        run: |
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
        id: configure_version

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #  with:
      #    version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        id: login

      #- name: Build and push image
      #  id: push
      #  uses: docker/build-push-action@v5.0.0
      #  with:
      #    push: ${{ github.event_name != 'pull_request' }}
      #    context: .
      #    push: true
      #    file: ./Dockerfile
      #    platforms: linux/amd64
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      #    labels: ${{ steps.meta.outputs.labels }}

      # --platform linux/amd64,linux/arm/v7,linux/arm64 \
      - name: Build caddy image
        id: build-and-push-caddy-cloudflare
        shell: bash
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            --progress plain \
            -t ghcr.io/${{ env.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            -f ./Dockerfile \
            "$@" \
            .

      - name: Build caddy alpine image
        id: build-and-push-caddy-cloudflare-alpine
        shell: bash
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            --progress plain \
            -t ghcr.io/${{ env.IMAGE_NAME }}:latest-alpine \
            -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-alpine \
            -f ./Dockerfile.alpine \
            "$@" \
            .

      #- name: Attest
      #  uses: actions/attest-build-provenance@v2
      #  id: attest
      #  with:
      #    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #    subject-digest: ${{ steps.push.outputs.digest }}
      #    push-to-registry: true

      #- uses: act10ns/slack@v1
      #  with:
      #    status: ${{ job.status }}
      #    steps: ${{ toJson(steps) }}
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #  if: failure()
